#pragma config(Motor,  port1,           rollerLeft,    tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           leftFront,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           leftBack,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           moGo,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           armLeft,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           armRight,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           lift,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           rightFront,    tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           rightBack,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port10,          rollerRight,   tmotorVex393_HBridge, openLoop)
/*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*/

#pragma platform(VEX2)
#pragma competitionControl(Competition)

#include "Vex_Competition_Includes.c"
#include "Header.h"

#define DEADZONE 20

void pre_auton() {
	bStopTasksBetweenModes = true;
}

task autonomous() {

	int leftM = 80, rightM = 80, mogoM = 120;

	//Drops the moving goal structure down
	motorReq[moGo] = - (mogoM);
	wait1Msec(500);

	//Moves forward for 3 seconds
	motorReq[leftFront] = leftM;
	motorReq[leftBack] = leftM;
	motorReq[rightFront] = rightM;
	motorReq[rightBack] = rightM;
	wait1Msec(3000);

	//Turns towards the left
	motorReq[leftFront] = -leftM;
	motorReq[leftBack] = -leftM;
	motorReq[rightFront] = rightM;
	motorReq[rightBack] = rightM;
	wait1Msec(500);

	//Moves forward for 1 seconds
	motorReq[leftFront] = leftM;
	motorReq[leftBack] = leftM;
	motorReq[rightFront] = rightM;
	motorReq[rightBack] = rightM;
	wait1Msec(1000);

	//Moves the mobile goal structure upwards
	motorReq[moGo] = mogoM;
	wait1Msec(50);


task usercontrol() {
	int leftC = 0, rightC = 0, moGoC = 0;
	int leftM = 0, rightM = 0, moGoM = 0;
	int roller = 0;
	int armC = 0;
	int liftC = 0;

	/*-----------------------------------------------------------------------------*/
/*                                                                             */
/*  Slew Rate control task                                                      */
/*  We still have to fix this up (NOT FUNCTIONAL)                              */
/*-----------------------------------------------------------------------------*/
/*	startTask(MotorSlewRateTask);
	while (true) {
		//drive train and mobile goal
		leftC = vexRT[Ch3];
		rightC = vexRT[Ch2];
		moGoC = vexRT[Btn6U] - vexRT[Btn6D];

		if(abs(leftC) > DEADZONE) {
				leftM = leftC;
		} else {
				leftM = 0;
		}

		if(abs(rightC) > DEADZONE) {
				rightM = rightC;
		} else {
				rightM = 0;
		}

		moGoM = 120*(moGoC);

		motorReq[leftFront] = leftM;
		motorReq[leftBack] = leftM;
		motorReq[rightFront] = rightM;
		motorReq[rightBack] = rightM;
		motorReq[moGo] = moGoM;



		//rubber roller intake
		int power = 50;
		roller = vexRT(Btn5U)-vexRT(Btn5DXmtr2);
		roller *= power;
		motorReq[rollerRight]= roller;
		motorReq[rollerLeft]= roller;

		//arm up and down
		int power1 = 115;
		armC = vexRT(Btn8UXmtr2) - vexRT(Btn8DXmtr2);
		armC *= power1;
		motorReq[armLeft] = armC;
		motorReq[armRight] = armC;

		//lift up and down
		int power2 = 127;
		liftC = vexRT(Btn6UXmtr2) - vexRT(Btn6DXmtr2);
		liftC *= power2;
		motorReq[lift] = liftC;



	}
}*/

/* THIS IS PID CONTROL CODE I FOUND ON VEX FORUM */
#pragma config(Sensor, dgtl1,  myEncoder,        sensorQuadEncoder)
#pragma config(Motor,  port10, myMotor,    tmotorNormal, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// PID using optical shaft encoder
//
// Shaft encoder has 360 pulses per revolution
//

#define PID_SENSOR_INDEX    myEncoder
#define PID_SENSOR_SCALE    1

#define PID_MOTOR_INDEX     myMotor
#define PID_MOTOR_SCALE     -1

#define PID_DRIVE_MAX       127
#define PID_DRIVE_MIN     (-127)

#define PID_INTEGRAL_LIMIT  50

// These could be constants but leaving
// as variables allows them to be modified in the debugger "live"
float  pid_Kp = 2.0;
float  pid_Ki = 0.04;
float  pid_Kd = 0.0;

static int   pidRunning = 1;
static float pidRequestedValue;

/*-----------------------------------------------------------------------------*/
/*                                                                             */
/*  pid control task                                                           */
/*                                                                             */
/*-----------------------------------------------------------------------------*/

task pidController()
{
    float  pidSensorCurrentValue;

    float  pidError;
    float  pidLastError;
    float  pidIntegral;
    float  pidDerivative;
    float  pidDrive;

    // If we are using an encoder then clear it
    if( SensorType[ PID_SENSOR_INDEX ] == sensorQuadEncoder )
        SensorValue[ PID_SENSOR_INDEX ] = 0;

    // Init the variables - thanks Glenn :)
    pidLastError  = 0;
    pidIntegral   = 0;

    while( true )
        {
        // Is PID control active ?
        if( pidRunning )
            {
            // Read the sensor value and scale
            pidSensorCurrentValue = SensorValue[ PID_SENSOR_INDEX ] * PID_SENSOR_SCALE;

            // calculate error
            pidError = pidSensorCurrentValue - pidRequestedValue;

            // integral - if Ki is not 0
            if( pid_Ki != 0 )
                {
                // If we are inside controlable window then integrate the error
                if( abs(pidError) < PID_INTEGRAL_LIMIT )
                    pidIntegral = pidIntegral + pidError;
                else
                    pidIntegral = 0;
                }
            else
                pidIntegral = 0;

            // calculate the derivative
            pidDerivative = pidError - pidLastError;
            pidLastError  = pidError;

            // calculate drive
            pidDrive = (pid_Kp * pidError) + (pid_Ki * pidIntegral) + (pid_Kd * pidDerivative);

            // limit drive
            if( pidDrive > PID_DRIVE_MAX )
                pidDrive = PID_DRIVE_MAX;
            if( pidDrive < PID_DRIVE_MIN )
                pidDrive = PID_DRIVE_MIN;

            // send to motor
            motor[ PID_MOTOR_INDEX ] = pidDrive * PID_MOTOR_SCALE;
            }
        else
            {
            // clear all
            pidError      = 0;
            pidLastError  = 0;
            pidIntegral   = 0;
            pidDerivative = 0;
            motor[ PID_MOTOR_INDEX ] = 0;
            }

        // Run at 50Hz
        wait1Msec( 25 );
        }
}

/*-----------------------------------------------------------------------------*/
/*                                                                             */
/*  main task                                                                  */
/*                                                                             */
/*-----------------------------------------------------------------------------*/

task main()
{
    // send the motor off somewhere
    pidRequestedValue = 1000;

    // start the PID task
    StartTask( pidController );

    // use joystick to modify the requested position
    while( true )
        {
        // maximum change for pidRequestedValue will be 127/4*20, around 640 counts per second
        // free spinning motor is 100rmp so 1.67 rotations per second
        // 1.67 * 360 counts is 600

        pidRequestedValue = pidRequestedValue + (vexRT[ Ch2 ]/4);

        wait1Msec(50);
        }

}
