#pragma config(Motor,  port2,           leftFront,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           leftBack,      tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           rightMoGo,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           rightFront,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           rightBack,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port10,          leftMoGo,      tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX2)
#pragma competitionControl(Competition)

#include "Vex_Competition_Includes.c"

#define DEADZONE 20

void pre_auton() {
	bStopTasksBetweenModes = true;
}

task autonomous() {

}


task usercontrol() {
	int leftC = 0, rightC = 0, moGoC = 0;
	int leftM = 0, rightM = 0, moGoM = 0;

	while (true) {
		leftC = vexRT[Ch3];
		rightC = vexRT[Ch2];
		moGoC = vexRT[Btn8U] - vexRT[Btn8D];

		if(abs(leftC) > DEADZONE) {
				leftM = leftC;
		} else {
				leftM = 0;
		}

		if(abs(rightC) > DEADZONE) {
				rightM = rightC;
		} else {
				rightM = 0;
		}

		moGoM = 120*(moGoC);

		motor[leftFront] = leftM;
		motor[leftBack] = leftM;
		motor[rightFront] = rightM;
		motor[rightBack] = rightM;
		motor[leftMoGo] = moGoM;
		motor[rightMoGo] = moGoM;
	}
}
