  	#pragma config(Motor,  port1,           rollerLeft,    tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           leftFront,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           leftBack,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           moGo,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           armLeft,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           armRight,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           lift,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           rightFront,    tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           rightBack,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port10,          rollerRight,   tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX2)
#pragma competitionControl(Competition)

#include "Vex_Competition_Includes.c"
#include "Header.h"

#define DEADZONE 20

void pre_auton() {
	bStopTasksBetweenModes = true;
}

task autonomous() {
	/*
	int leftM = 80, rightM = 80, mogoM = 120;

	//Drops the moving goal structure down
	motorReq[moGo] = - (mogoM);
	wait1Msec(500);

	//Moves forward for 3 seconds
	motorReq[leftFront] = leftM;
	motorReq[leftBack] = leftM;
	motorReq[rightFront] = rightM;
	motorReq[rightBack] = rightM;
	wait1Msec(3000);

	//Turns towards the left
	motorReq[leftFront] = -leftM;
	motorReq[leftBack] = -leftM;
	motorReq[rightFront] = rightM;
	motorReq[rightBack] = rightM;
	wait1Msec(500);

	//Moves forward for 1 seconds
	motorReq[leftFront] = leftM;
	motorReq[leftBack] = leftM;
	motorReq[rightFront] = rightM;
	motorReq[rightBack] = rightM;
	wait1Msec(1000);

	//Moves the mobile goal structure upwards
	motorReq[moGo] = mogoM;
	wait1Msec(50);
	*/
}

task usercontrol() {
	int leftC = 0, rightC = 0, moGoC = 0;
	int leftM = 0, rightM = 0, moGoM = 0;
	int roller = 0;
	int armC = 0;
	int liftC = 0;
	startTask(MotorSlewRateTask);
	while (true) {
		//drive train and mobile goal
		leftC = vexRT[Ch3];
		rightC = vexRT[Ch2];
		moGoC = vexRT[Btn6U] - vexRT[Btn6D];

		if(abs(leftC) > DEADZONE) {
				leftM = leftC;
		} else {
				leftM = 0;
		}

		if(abs(rightC) > DEADZONE) {
				rightM = rightC;
		} else {
				rightM = 0;
		}

		moGoM = 120*(moGoC);

		motorReq[leftFront] = leftM;
		motorReq[leftBack] = leftM;
		motorReq[rightFront] = rightM;
		motorReq[rightBack] = rightM;
		motorReq[moGo] = moGoM;



		//rubber roller intake
		int power = 50;
		roller = vexRT(Btn5U)-vexRT(Btn5DXmtr2);
		roller *= power;
		motorReq[rollerRight]= roller;
		motorReq[rollerLeft]= roller;

		//arm up and down
		int power1 = 115;
		armC = vexRT(Btn8UXmtr2) - vexRT(Btn8DXmtr2);
		armC *= power1;
		motorReq[armLeft] = armC;
		motorReq[armRight] = armC;

		//lift up and down
		int power2 = 127;
		liftC = vexRT(Btn6UXmtr2) - vexRT(Btn6DXmtr2);
		liftC *= power2;
		motorReq[lift] = liftC;
	}
}
